### ISSUE TITLE
Stop rounding displayed ranks to the nearest 100

### ISSUE THREAD

**Issue by ChrisKitching** [FAForever/lobby#164]
Why do we do this?

Those "00"s are just needlessly filling space in the UI, for one thing, and it makes the degree of "jumpiness" of your observable rank sufficiently large as to be quite annoying.

Does anyone know the history behind this decision (@Sheeo?), or shall we just stop doing it?

**Comment by IDragonfire** [comment]
First we have exact ranks, like 1134 or 123,
I am not sure, but people interpret it wrong and that was the reason to round it.

**Comment by VoRGoR** [comment]
Zep wished to obscure the rating to avoid people from being so ragey when they lost points.
I'm not sure if you were there before it was like this, but there was a lot of that.
To be honest, I kind of like the obfuscated rating.
The jump isn't really too bad, either. I'm not exactly sure, but I think 100 rating points difference gives you a very small (less than 10%?) difference - and remember, you are not performing the same - the rating is more an average of how you perform, you being unlikely to perform UNDER this.

**Comment by ChrisKitching** [comment]
I realise that we store precise ranks (and you can get at them via the "show player stats" button), but it seems pretty strange to obfuscate this in the lobby. Surely the complete information about others should be consistently hidden, or consistently non-hidden?

In what way were people interpreting it wrong?

The issue of people being "ragey" when they lost points seems like it could be better solved by only updating the ranking daily (or every few hours). That way, the immediate reduction produced by having a frustratingly terrible game isn't jammed in your face (which is presumably the source of the frustration).

How much of a difference 100 rating points makes is surely a function of your current rating. When you're around 200, a jump to 300 is an increase of 50%: this seems sufficient to hurl you into a game you might be ill-prepared for.

Lastly, there's the issue of the UI: the last two digits of every ranking shown in the lobby convey zero information. If the rounding is to be retained, it seems sensible to start truncating the displayed value, as well.

**Comment by IDragonfire** [comment]
From UI side it is terrible ...

Interpreting:
If some people host ranking restricted games, e.g. over 800,
people use the two diggest to try to decice if they fit into the game ...
or they prefer a 810 one over a 790 one ...

**Comment by VoRGoR** [comment]
I can gurantee the level around 0-700 varies wildly, there's not much difference there.
Remember, these small differences in rating are statistical, and again, your rating is not a single number, it's a level you're unlikely to perform under.

Zep also tried a system where it would update periodically, but that didn't really help either.
In the end, a system where it slightly obscures the rating means that people have less to "show off" , as it were  - zep was very fond of the term e-penis to describe people's obsession with rating
About the show player stats, I actually think he just forgot, or thought that it wasn't useful enough to be relevant. Can't know without asking him directly.

**Comment by ChrisKitching** [comment]
@IDragonfire I'm having a little trouble understanding that post. I think the point you're trying to make is that, given an "over 800" game, the last two digits might be used to rather insensibly prevent a 790 player from joining.
If the notion of rating is supposed to be "minimum likely performance level", then this rounding-up we've performed violates the supposed meaning of the value. That said, at 800 the maximum possible rounding error is a mere 5%, so we probably don't care too much.

@VoRGoR You're right, rating is ostensibly a level you're unlikely to perform under. With the rounding, we introduce an additional error of up to 50 points to this. Perhaps we should always round down, then, to remain true to the notion of "minimum performance". As I said above, though, at 800 this is just a 5% error. If we are *very sure* that the noise level in the 0-700 range is sufficiently high that we don't care too much about those scores, then I'm leaning ever more towards introducing a sort of "levels" system (AKA, rank/100).

I'd like to hear more about how periodical updates "didn't really help". What exactly went wrong?

I'm not sure you can actually get away from the "e-penis effect" and still have a rating system. People are still very keen to show off their large integers, and I still get shouted at and evicted from games because my integer is deemed slightly too low. This is just the price you have to pay for having a rating system (which, in general, seems to be a useful thing to have).
It is folly to attempt to make something idiot proof: if you succeed, nature will simply furnish you with a better idiot.

**Comment by IDragonfire** [comment]
@ChrisKitching 
The problem is that people don't understand the rating ;)

**Comment by ChrisKitching** [comment]
@IDragonfire How so?
Which aspects of it do people fail to understand that produce problems?

Once we know that, we might have a good approach for starting to mitigate the problem. As I said above, though, it's unreasonable to expect to be able to achieve 100% idiot-proofing in any system.

**Comment by VoRGoR** [comment]
You are correct about people always wanting to show off ^^ 
I do think though that there has been less of that since the rounding, no proof, just from what I remember.

The periodical updates just made people angry because they didn't bother to listen to the announcements that it was going to happen, so they thought their rating wasn't changing (and trust me, it wasn't due to lack of communication, it was announced many times and was even in the topic) 
And instead of getting an instant rage after a loss of points, it was merely delayed until it was updated.

You are probably on to something with rounding down.
50 points either way as we've mentioned are extremely small statistically, so it's not urgent, but this certainly bears thought.
Possibly if we keep the rounding a smaller interval could be used (so you would have 950, 1000, 1050)

You're exactly right about the idiot-proof thing.
Dragon is also correct about people not understanding what the rating is, even when it's explained ^^

**Comment by ChrisKitching** [comment]
> I do think though that there has been less of that since the rounding, no proof, just from what I remember.

Let's try and avoid "appeal to anecdote" and "appeal to authority". Both are just liable to lead us to limit the scope of our thinking.

> The periodical updates just made people angry because they didn't bother to listen to the announcements that it was going to happen

This seems like a non-problem? We've established that idiot-proofing isn't achievable. Make the system work well for a sane user, and tactfully ignore the rabid screaming of people who don't care enough to read.

> so they thought their rating wasn't changing

Perhaps the solution is to have two values: A "provisional rating" (an instantaneously-updating one visible only from your "show player stats" screen) and a "display rating" (a periodically-updating one visible to the rest of the world. We just copy the "provisional rating" onto the "display rating" at regular intervals).
I actually now prefer this to my initial suggestion of "just get rid of rounding".

That way, you can see your instantaneous score changes by viewing your stats page, but it isn't rubbed in your face while you're in the "frustrated because you just lost really badly" state.

I also suspect that, having lived with the current very-coarse-rounding system for a long time, people are used to not seeing instant rating upgrades, so you won't have a similar reaction again.

> And instead of getting an instant rage after a loss of points, it was merely delayed until it was updated.

It seems that this problem cannot be fully solved while still having a ranking system.
The contribution rounding makes to solving this problem is, essentially, damping. It dampens the jitter your ranking experiences due to short-term losses. A time or number-of-games based damping system would be just as effective, but wouldn't discard otherwise-useful information.

> Possibly if we keep the rounding a smaller interval could be used (so you would have 950, 1000, 1050)

That would definitely be an improvement.

> Dragon is also correct about people not understanding what the rating is, even when it's explained ^^

One problem I've encountered is that it doesn't seem to be explained anywhere easily reachable from the game client. I've only developed any sort of understanding of it since I started contributing code here. Some documentation to explain to the average user how it actually works might be appreciated.
It wouldn't be idiot-proofing (impossible, remember?), but it'd make the experience better for frustrated non-idiots ;)

**Comment by VoRGoR** [comment]
How the heck do I quote things

**Comment by IDragonfire** [comment]
>How the heck do I quote things

@VoRGoR 
https://guides.github.com/features/mastering-markdown/
See Header & Quote

**Comment by VoRGoR** [comment]
> Let's try and avoid "appeal to anecdote" and "appeal to authority". Both are just liable to lead us to limit the scope of our thinking.

Hey, I already said I didn't have any proof, it's just my memory. There's no need to bash people for trying to help.

> This seems like a non-problem? We've established that idiot-proofing isn't achievable. Make the system work well for a sane user, and tactfully ignore the rabid screaming of people who don't care enough to read.

This was something that got to Ze_PilOt too much I think. You're right (again) about idiotproofing.

> It seems that this problem cannot be fully solved while still having a ranking system.
> That way, you can see your instantaneous score changes by viewing your stats page, but it isn't rubbed in your face while you're in the "frustrated because you just lost really badly" state.

All I'm saying is that delaying it doesn't really solve anything, and adding it again now seems rather redundant. I don't think people will change their opinions due to a slight difference in how it works either.
I also believe people will just react to lack of roundings and delayed updates  - I thought we already established about the idiots part ^^





> One problem I've encountered is that it doesn't seem to be explained anywhere easily reachable from the game client.

This is certainly true, it's on the wiki already. However the wiki is not well known, not well advertised and considerably out of date. I know people who want to help update the wiki, but currently registration for that is broken. It's on a tofix list afaik, I'll raise that again later.

**Comment by aeoncleanse** [comment]
Rounded ratings are just better. I'm sure Gorton will attest to a distinct drop in the amount of rage behaviour related to ratings rising/falling. It's easier to tell at a glance roughly how good someone is. It's easier to balance teams in a lobby as host, because your brain deals naturally better with rounded numbers.

There's no point in arguing this based on what rating is, the only thing of concern is what the rating is PERCEIVED to mean by the vast majority, however wrong that it. This is one of the few decisions PilOt made about the rating system that I whole-heartedly agree with. If you want to keep track of your own rating, or compare to someone else's, use the view details function (Which, incidentally, should be improved, it's buggy as all hell right now!)

**Comment by Sheeo** [comment]
So, as background information; the standard starting mean for TrueSkill is `25`. I believe implementations that use trueskill do not normally show decimals, so this is equivalent in our case to rounding to the nearest 100.

I believe using standard trueskill median values would be a good choice, if we are to continue rounding, aligned with the suggestion of @ChrisKitching.

Nowhere in the python lobby are trueskill values rounded, however. We should spin off this discussion into FAForever/fa or even the server repository, incase we really want to hide the additional information.
